// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: contract.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TicketService_NewTicket_FullMethodName            = "/pb.TicketService/NewTicket"
	TicketService_NewUser_FullMethodName              = "/pb.TicketService/NewUser"
	TicketService_NewSupport_FullMethodName           = "/pb.TicketService/NewSupport"
	TicketService_GetUserTickets_FullMethodName       = "/pb.TicketService/GetUserTickets"
	TicketService_GetSupportTickets_FullMethodName    = "/pb.TicketService/GetSupportTickets"
	TicketService_GetTicketsWithStatus_FullMethodName = "/pb.TicketService/GetTicketsWithStatus"
	TicketService_CloseTicket_FullMethodName          = "/pb.TicketService/CloseTicket"
	TicketService_AnswerTicket_FullMethodName         = "/pb.TicketService/AnswerTicket"
	TicketService_TransferTicket_FullMethodName       = "/pb.TicketService/TransferTicket"
)

// TicketServiceClient is the client API for TicketService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TicketServiceClient interface {
	NewTicket(ctx context.Context, in *NewTicketRequest, opts ...grpc.CallOption) (*NewTicketResponse, error)
	NewUser(ctx context.Context, in *NewUserRequest, opts ...grpc.CallOption) (*NewUserResponse, error)
	NewSupport(ctx context.Context, in *NewSupportRequest, opts ...grpc.CallOption) (*NewSupportResponse, error)
	GetUserTickets(ctx context.Context, in *GetUserTicketsRequest, opts ...grpc.CallOption) (*GetUserTicketsResponse, error)
	GetSupportTickets(ctx context.Context, in *GetSupportTicketsRequest, opts ...grpc.CallOption) (*GetSupportTicketsResponse, error)
	GetTicketsWithStatus(ctx context.Context, in *GetTicketsWithStatusRequest, opts ...grpc.CallOption) (*GetTicketsWithStatusResponse, error)
	CloseTicket(ctx context.Context, in *CloseTicketRequest, opts ...grpc.CallOption) (*CloseTicketResponse, error)
	AnswerTicket(ctx context.Context, in *AnswerTicketRequest, opts ...grpc.CallOption) (*AnswerTicketResponse, error)
	TransferTicket(ctx context.Context, in *TransferTicketRequest, opts ...grpc.CallOption) (*TransferTicketResponse, error)
}

type ticketServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTicketServiceClient(cc grpc.ClientConnInterface) TicketServiceClient {
	return &ticketServiceClient{cc}
}

func (c *ticketServiceClient) NewTicket(ctx context.Context, in *NewTicketRequest, opts ...grpc.CallOption) (*NewTicketResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NewTicketResponse)
	err := c.cc.Invoke(ctx, TicketService_NewTicket_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ticketServiceClient) NewUser(ctx context.Context, in *NewUserRequest, opts ...grpc.CallOption) (*NewUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NewUserResponse)
	err := c.cc.Invoke(ctx, TicketService_NewUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ticketServiceClient) NewSupport(ctx context.Context, in *NewSupportRequest, opts ...grpc.CallOption) (*NewSupportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NewSupportResponse)
	err := c.cc.Invoke(ctx, TicketService_NewSupport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ticketServiceClient) GetUserTickets(ctx context.Context, in *GetUserTicketsRequest, opts ...grpc.CallOption) (*GetUserTicketsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserTicketsResponse)
	err := c.cc.Invoke(ctx, TicketService_GetUserTickets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ticketServiceClient) GetSupportTickets(ctx context.Context, in *GetSupportTicketsRequest, opts ...grpc.CallOption) (*GetSupportTicketsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSupportTicketsResponse)
	err := c.cc.Invoke(ctx, TicketService_GetSupportTickets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ticketServiceClient) GetTicketsWithStatus(ctx context.Context, in *GetTicketsWithStatusRequest, opts ...grpc.CallOption) (*GetTicketsWithStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTicketsWithStatusResponse)
	err := c.cc.Invoke(ctx, TicketService_GetTicketsWithStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ticketServiceClient) CloseTicket(ctx context.Context, in *CloseTicketRequest, opts ...grpc.CallOption) (*CloseTicketResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CloseTicketResponse)
	err := c.cc.Invoke(ctx, TicketService_CloseTicket_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ticketServiceClient) AnswerTicket(ctx context.Context, in *AnswerTicketRequest, opts ...grpc.CallOption) (*AnswerTicketResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnswerTicketResponse)
	err := c.cc.Invoke(ctx, TicketService_AnswerTicket_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ticketServiceClient) TransferTicket(ctx context.Context, in *TransferTicketRequest, opts ...grpc.CallOption) (*TransferTicketResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransferTicketResponse)
	err := c.cc.Invoke(ctx, TicketService_TransferTicket_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TicketServiceServer is the server API for TicketService service.
// All implementations must embed UnimplementedTicketServiceServer
// for forward compatibility.
type TicketServiceServer interface {
	NewTicket(context.Context, *NewTicketRequest) (*NewTicketResponse, error)
	NewUser(context.Context, *NewUserRequest) (*NewUserResponse, error)
	NewSupport(context.Context, *NewSupportRequest) (*NewSupportResponse, error)
	GetUserTickets(context.Context, *GetUserTicketsRequest) (*GetUserTicketsResponse, error)
	GetSupportTickets(context.Context, *GetSupportTicketsRequest) (*GetSupportTicketsResponse, error)
	GetTicketsWithStatus(context.Context, *GetTicketsWithStatusRequest) (*GetTicketsWithStatusResponse, error)
	CloseTicket(context.Context, *CloseTicketRequest) (*CloseTicketResponse, error)
	AnswerTicket(context.Context, *AnswerTicketRequest) (*AnswerTicketResponse, error)
	TransferTicket(context.Context, *TransferTicketRequest) (*TransferTicketResponse, error)
	mustEmbedUnimplementedTicketServiceServer()
}

// UnimplementedTicketServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTicketServiceServer struct{}

func (UnimplementedTicketServiceServer) NewTicket(context.Context, *NewTicketRequest) (*NewTicketResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method NewTicket not implemented")
}
func (UnimplementedTicketServiceServer) NewUser(context.Context, *NewUserRequest) (*NewUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method NewUser not implemented")
}
func (UnimplementedTicketServiceServer) NewSupport(context.Context, *NewSupportRequest) (*NewSupportResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method NewSupport not implemented")
}
func (UnimplementedTicketServiceServer) GetUserTickets(context.Context, *GetUserTicketsRequest) (*GetUserTicketsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserTickets not implemented")
}
func (UnimplementedTicketServiceServer) GetSupportTickets(context.Context, *GetSupportTicketsRequest) (*GetSupportTicketsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSupportTickets not implemented")
}
func (UnimplementedTicketServiceServer) GetTicketsWithStatus(context.Context, *GetTicketsWithStatusRequest) (*GetTicketsWithStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTicketsWithStatus not implemented")
}
func (UnimplementedTicketServiceServer) CloseTicket(context.Context, *CloseTicketRequest) (*CloseTicketResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CloseTicket not implemented")
}
func (UnimplementedTicketServiceServer) AnswerTicket(context.Context, *AnswerTicketRequest) (*AnswerTicketResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AnswerTicket not implemented")
}
func (UnimplementedTicketServiceServer) TransferTicket(context.Context, *TransferTicketRequest) (*TransferTicketResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TransferTicket not implemented")
}
func (UnimplementedTicketServiceServer) mustEmbedUnimplementedTicketServiceServer() {}
func (UnimplementedTicketServiceServer) testEmbeddedByValue()                       {}

// UnsafeTicketServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TicketServiceServer will
// result in compilation errors.
type UnsafeTicketServiceServer interface {
	mustEmbedUnimplementedTicketServiceServer()
}

func RegisterTicketServiceServer(s grpc.ServiceRegistrar, srv TicketServiceServer) {
	// If the following call panics, it indicates UnimplementedTicketServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TicketService_ServiceDesc, srv)
}

func _TicketService_NewTicket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewTicketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketServiceServer).NewTicket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TicketService_NewTicket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketServiceServer).NewTicket(ctx, req.(*NewTicketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TicketService_NewUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketServiceServer).NewUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TicketService_NewUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketServiceServer).NewUser(ctx, req.(*NewUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TicketService_NewSupport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewSupportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketServiceServer).NewSupport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TicketService_NewSupport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketServiceServer).NewSupport(ctx, req.(*NewSupportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TicketService_GetUserTickets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserTicketsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketServiceServer).GetUserTickets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TicketService_GetUserTickets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketServiceServer).GetUserTickets(ctx, req.(*GetUserTicketsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TicketService_GetSupportTickets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSupportTicketsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketServiceServer).GetSupportTickets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TicketService_GetSupportTickets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketServiceServer).GetSupportTickets(ctx, req.(*GetSupportTicketsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TicketService_GetTicketsWithStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTicketsWithStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketServiceServer).GetTicketsWithStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TicketService_GetTicketsWithStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketServiceServer).GetTicketsWithStatus(ctx, req.(*GetTicketsWithStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TicketService_CloseTicket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseTicketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketServiceServer).CloseTicket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TicketService_CloseTicket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketServiceServer).CloseTicket(ctx, req.(*CloseTicketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TicketService_AnswerTicket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnswerTicketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketServiceServer).AnswerTicket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TicketService_AnswerTicket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketServiceServer).AnswerTicket(ctx, req.(*AnswerTicketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TicketService_TransferTicket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransferTicketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketServiceServer).TransferTicket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TicketService_TransferTicket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketServiceServer).TransferTicket(ctx, req.(*TransferTicketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TicketService_ServiceDesc is the grpc.ServiceDesc for TicketService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TicketService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.TicketService",
	HandlerType: (*TicketServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NewTicket",
			Handler:    _TicketService_NewTicket_Handler,
		},
		{
			MethodName: "NewUser",
			Handler:    _TicketService_NewUser_Handler,
		},
		{
			MethodName: "NewSupport",
			Handler:    _TicketService_NewSupport_Handler,
		},
		{
			MethodName: "GetUserTickets",
			Handler:    _TicketService_GetUserTickets_Handler,
		},
		{
			MethodName: "GetSupportTickets",
			Handler:    _TicketService_GetSupportTickets_Handler,
		},
		{
			MethodName: "GetTicketsWithStatus",
			Handler:    _TicketService_GetTicketsWithStatus_Handler,
		},
		{
			MethodName: "CloseTicket",
			Handler:    _TicketService_CloseTicket_Handler,
		},
		{
			MethodName: "AnswerTicket",
			Handler:    _TicketService_AnswerTicket_Handler,
		},
		{
			MethodName: "TransferTicket",
			Handler:    _TicketService_TransferTicket_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "contract.proto",
}
