// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: contract.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NewTicketRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        string                 `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	Body          string                 `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewTicketRequest) Reset() {
	*x = NewTicketRequest{}
	mi := &file_contract_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewTicketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewTicketRequest) ProtoMessage() {}

func (x *NewTicketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contract_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewTicketRequest.ProtoReflect.Descriptor instead.
func (*NewTicketRequest) Descriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{0}
}

func (x *NewTicketRequest) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *NewTicketRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type NewTicketResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	TicketID      string                 `protobuf:"bytes,3,opt,name=ticketID,proto3" json:"ticketID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewTicketResponse) Reset() {
	*x = NewTicketResponse{}
	mi := &file_contract_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewTicketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewTicketResponse) ProtoMessage() {}

func (x *NewTicketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contract_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewTicketResponse.ProtoReflect.Descriptor instead.
func (*NewTicketResponse) Descriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{1}
}

func (x *NewTicketResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *NewTicketResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *NewTicketResponse) GetTicketID() string {
	if x != nil {
		return x.TicketID
	}
	return ""
}

type NewUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewUserRequest) Reset() {
	*x = NewUserRequest{}
	mi := &file_contract_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewUserRequest) ProtoMessage() {}

func (x *NewUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contract_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewUserRequest.ProtoReflect.Descriptor instead.
func (*NewUserRequest) Descriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{2}
}

func (x *NewUserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type NewUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	UserID        string                 `protobuf:"bytes,3,opt,name=userID,proto3" json:"userID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewUserResponse) Reset() {
	*x = NewUserResponse{}
	mi := &file_contract_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewUserResponse) ProtoMessage() {}

func (x *NewUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contract_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewUserResponse.ProtoReflect.Descriptor instead.
func (*NewUserResponse) Descriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{3}
}

func (x *NewUserResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *NewUserResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *NewUserResponse) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

type NewSupportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewSupportRequest) Reset() {
	*x = NewSupportRequest{}
	mi := &file_contract_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewSupportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewSupportRequest) ProtoMessage() {}

func (x *NewSupportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contract_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewSupportRequest.ProtoReflect.Descriptor instead.
func (*NewSupportRequest) Descriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{4}
}

func (x *NewSupportRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type NewSupportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	SupportID     string                 `protobuf:"bytes,3,opt,name=supportID,proto3" json:"supportID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewSupportResponse) Reset() {
	*x = NewSupportResponse{}
	mi := &file_contract_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewSupportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewSupportResponse) ProtoMessage() {}

func (x *NewSupportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contract_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewSupportResponse.ProtoReflect.Descriptor instead.
func (*NewSupportResponse) Descriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{5}
}

func (x *NewSupportResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *NewSupportResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *NewSupportResponse) GetSupportID() string {
	if x != nil {
		return x.SupportID
	}
	return ""
}

var File_contract_proto protoreflect.FileDescriptor

const file_contract_proto_rawDesc = "" +
	"\n" +
	"\x0econtract.proto\x12\x02pb\">\n" +
	"\x10NewTicketRequest\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\tR\x06userID\x12\x12\n" +
	"\x04body\x18\x02 \x01(\tR\x04body\"_\n" +
	"\x11NewTicketResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x1a\n" +
	"\bticketID\x18\x03 \x01(\tR\bticketID\"$\n" +
	"\x0eNewUserRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"Y\n" +
	"\x0fNewUserResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x16\n" +
	"\x06userID\x18\x03 \x01(\tR\x06userID\"'\n" +
	"\x11NewSupportRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"b\n" +
	"\x12NewSupportResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x1c\n" +
	"\tsupportID\x18\x03 \x01(\tR\tsupportID2\xc0\x01\n" +
	"\rTicketService\x12:\n" +
	"\tNewTicket\x12\x14.pb.NewTicketRequest\x1a\x15.pb.NewTicketResponse\"\x00\x124\n" +
	"\aNewUser\x12\x12.pb.NewUserRequest\x1a\x13.pb.NewUserResponse\"\x00\x12=\n" +
	"\n" +
	"NewSupport\x12\x15.pb.NewSupportRequest\x1a\x16.pb.NewSupportResponse\"\x00B#Z!ticket_service/internal/protos;pbb\x06proto3"

var (
	file_contract_proto_rawDescOnce sync.Once
	file_contract_proto_rawDescData []byte
)

func file_contract_proto_rawDescGZIP() []byte {
	file_contract_proto_rawDescOnce.Do(func() {
		file_contract_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_contract_proto_rawDesc), len(file_contract_proto_rawDesc)))
	})
	return file_contract_proto_rawDescData
}

var file_contract_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_contract_proto_goTypes = []any{
	(*NewTicketRequest)(nil),   // 0: pb.NewTicketRequest
	(*NewTicketResponse)(nil),  // 1: pb.NewTicketResponse
	(*NewUserRequest)(nil),     // 2: pb.NewUserRequest
	(*NewUserResponse)(nil),    // 3: pb.NewUserResponse
	(*NewSupportRequest)(nil),  // 4: pb.NewSupportRequest
	(*NewSupportResponse)(nil), // 5: pb.NewSupportResponse
}
var file_contract_proto_depIdxs = []int32{
	0, // 0: pb.TicketService.NewTicket:input_type -> pb.NewTicketRequest
	2, // 1: pb.TicketService.NewUser:input_type -> pb.NewUserRequest
	4, // 2: pb.TicketService.NewSupport:input_type -> pb.NewSupportRequest
	1, // 3: pb.TicketService.NewTicket:output_type -> pb.NewTicketResponse
	3, // 4: pb.TicketService.NewUser:output_type -> pb.NewUserResponse
	5, // 5: pb.TicketService.NewSupport:output_type -> pb.NewSupportResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_contract_proto_init() }
func file_contract_proto_init() {
	if File_contract_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_contract_proto_rawDesc), len(file_contract_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_contract_proto_goTypes,
		DependencyIndexes: file_contract_proto_depIdxs,
		MessageInfos:      file_contract_proto_msgTypes,
	}.Build()
	File_contract_proto = out.File
	file_contract_proto_goTypes = nil
	file_contract_proto_depIdxs = nil
}
