// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: contract.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NewTicketRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TicketID      string                 `protobuf:"bytes,1,opt,name=ticketID,proto3" json:"ticketID,omitempty"`
	UserID        string                 `protobuf:"bytes,2,opt,name=userID,proto3" json:"userID,omitempty"`
	Body          string                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewTicketRequest) Reset() {
	*x = NewTicketRequest{}
	mi := &file_contract_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewTicketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewTicketRequest) ProtoMessage() {}

func (x *NewTicketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contract_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewTicketRequest.ProtoReflect.Descriptor instead.
func (*NewTicketRequest) Descriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{0}
}

func (x *NewTicketRequest) GetTicketID() string {
	if x != nil {
		return x.TicketID
	}
	return ""
}

func (x *NewTicketRequest) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *NewTicketRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type NewTicketResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewTicketResponse) Reset() {
	*x = NewTicketResponse{}
	mi := &file_contract_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewTicketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewTicketResponse) ProtoMessage() {}

func (x *NewTicketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contract_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewTicketResponse.ProtoReflect.Descriptor instead.
func (*NewTicketResponse) Descriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{1}
}

func (x *NewTicketResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_contract_proto protoreflect.FileDescriptor

const file_contract_proto_rawDesc = "" +
	"\n" +
	"\x0econtract.proto\x12\x02pb\"Z\n" +
	"\x10NewTicketRequest\x12\x1a\n" +
	"\bticketID\x18\x01 \x01(\tR\bticketID\x12\x16\n" +
	"\x06userID\x18\x02 \x01(\tR\x06userID\x12\x12\n" +
	"\x04body\x18\x03 \x01(\tR\x04body\")\n" +
	"\x11NewTicketResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value2K\n" +
	"\rTicketService\x12:\n" +
	"\tNewTicket\x12\x14.pb.NewTicketRequest\x1a\x15.pb.NewTicketResponse\"\x00B\x1cZ\x1agateway/internal/protos;pbb\x06proto3"

var (
	file_contract_proto_rawDescOnce sync.Once
	file_contract_proto_rawDescData []byte
)

func file_contract_proto_rawDescGZIP() []byte {
	file_contract_proto_rawDescOnce.Do(func() {
		file_contract_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_contract_proto_rawDesc), len(file_contract_proto_rawDesc)))
	})
	return file_contract_proto_rawDescData
}

var file_contract_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_contract_proto_goTypes = []any{
	(*NewTicketRequest)(nil),  // 0: pb.NewTicketRequest
	(*NewTicketResponse)(nil), // 1: pb.NewTicketResponse
}
var file_contract_proto_depIdxs = []int32{
	0, // 0: pb.TicketService.NewTicket:input_type -> pb.NewTicketRequest
	1, // 1: pb.TicketService.NewTicket:output_type -> pb.NewTicketResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_contract_proto_init() }
func file_contract_proto_init() {
	if File_contract_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_contract_proto_rawDesc), len(file_contract_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_contract_proto_goTypes,
		DependencyIndexes: file_contract_proto_depIdxs,
		MessageInfos:      file_contract_proto_msgTypes,
	}.Build()
	File_contract_proto = out.File
	file_contract_proto_goTypes = nil
	file_contract_proto_depIdxs = nil
}
