services:
  postgres:
    image: postgres:18
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRE_DB}
      POSTGRES_USER: ${POSTGRE_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ticket -d ticket"]
      interval: 5s
      timeout: 5s
      retries: 10

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    container_name: gateway
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      ticket-service:
        condition: service_started
    environment:
      PORT: ${GATEWAY_HTTP_PORT}
      TICKET-HOST: ${TICKET_GRPC_HOST}
      TICKET-PORT: ${TICKET_GRPC_PORT}
    ports:
      - "${GATEWAY_HTTP_PORT}:${GATEWAY_HTTP_PORT}"

  ticket-service:
    build:
      context: ./ticket_service
      dockerfile: Dockerfile
    container_name: ${TICKET_GRPC_HOST}
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      POSTGRES_HOST: ${POSTGRE_HOST}
      POSTGRES_PORT: ${POSTGRE_PORT}
      POSTGRES_DB: ${POSTGRE_DB}
      POSTGRES_USER: ${POSTGRE_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRE_PASSWORD}
      PORT: ${TICKET_GRPC_PORT}
    ports:
      - "${TICKET_GRPC_PORT}:${TICKET_GRPC_PORT}"

volumes:
  postgres_data:
