services:
  postgres:
    image: postgres:18
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRE_DBNAME}
      POSTGRES_USER: ${POSTGRE_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ticket -d ticket"]
      interval: 5s
      timeout: 5s
      retries: 10

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    container_name: gateway
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      ticket-service:
        condition: service_started
    environment:
      PORT: ${GATEWAY_HTTP_PORT}
      TICKET-HOST: ${TICKET_GRPC_HOST}
      TICKET-PORT: ${TICKET_GRPC_PORT}
    ports:
      - "${GATEWAY_HTTP_PORT}:${GATEWAY_HTTP_PORT}"

  ticket-service:
    build:
      context: ./ticket_service
      dockerfile: Dockerfile
    container_name: ${TICKET_GRPC_HOST}
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      POSTGRES_HOST: ${POSTGRE_HOST}
      POSTGRES_PORT: ${POSTGRE_PORT}
      POSTGRES_DB: ${POSTGRE_DBNAME}
      POSTGRES_USER: ${POSTGRE_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRE_PASSWORD}
      PORT: ${TICKET_GRPC_PORT}
    ports:
      - "${TICKET_GRPC_PORT}:${TICKET_GRPC_PORT}"
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.52.0
    container_name: cadvisor
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /dev/disk:/dev/disk:ro

  prometheus:
    image: prom/prometheus:v3.8.0
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    depends_on:
      - cadvisor
volumes:
  postgres_data:
  prometheus_data:
