syntax = "proto3";

package pb;

option go_package = "ticket_service/internal/protos;pb";

service TicketService {
  rpc NewTicket (NewTicketRequest) returns (NewTicketResponse) {}
  rpc NewUser (NewUserRequest) returns (NewUserResponse) {}
}

message NewTicketRequest {
  string userID = 1;
  string body = 2;
}

message NewTicketResponse {
  bool success = 1;
  string error = 2;
  string ticketID = 3;
}

message NewUserRequest {
  string name = 1;
}

message NewUserResponse {
  bool success = 1;
  string error = 2;
  string userID = 3;
}