ALTER TABLE supports
    ALTER COLUMN id DROP DEFAULT;

ALTER TABLE ticket_responses
    ALTER COLUMN id DROP DEFAULT;

ALTER TABLE tickets
    ALTER COLUMN id DROP DEFAULT;

ALTER TABLE users
    ALTER COLUMN id DROP DEFAULT;
